### ISSUE TITLE
Arte da camisa - edição 2016

### ISSUE THREAD

**Issue by glaucocustodio** [rupycampinas/branding#1]
Fala pessoal, beleza? Esse ano queremos fazer algo diferente na camisa dos participantes da RuPy Campinas 2016.

Estamos abrindo um concurso para escolha de arte da camisa. Como funcionará?

Faça sua arte em vetor (de preferência em .ai ou .cdr), exporte como imagem (jpg ou png) e responda a essa issue com ela em anexo para que possamos visualizar. Não esqueça de dar um nome para sua criação xD.

Único requisito é que deve conter o logo da RuPy ([logo-rupy.ai.zip](https://github.com/rupycampinas/branding/files/103153/logo-rupy.ai.zip)) e o endereço do site (campinas.rupy.com.br).

A arte vencedora será escolhida pela organização do evento, levando em conta os seguintes critérios:

- identificação com o evento (tema, cores)
- criatividade
- aceitação da comunidade (através de comentários nessa issue)

O responsável pelo design da camisa ganhará 2 ingressos para o evento e também terá seu nome divulgado nas redes sociais como forma de agradecimento.

Obs: não há limite de sugestões por participante.

Boa sorte a todos.

**Comment by robindesu** [comment]
LEgal a iniciativa vou tentar participar!

**Comment by desk467** [comment]
> Faça sua arte em vetor (de preferência em .ai ou .cdr), exporte como imagem (jpg ou png) e responda a essa issue com ela em anexo para que possamos visualizar. Não esqueça de dar um nome para sua criação xD.

Não rola .svg ? :cry:

**Comment by pedrobarrostech** [comment]
Segue minha sugestão de modelo.

[arvoredeideias-camisetarupy.zip](https://github.com/rupycampinas/branding/files/149476/arvoredeideias-camisetarupy.zip)

**Comment by guivr** [comment]
Antes tarde do que nunca! :)

Minha sugestao combina umas das melhores coisas do universo: unicamp e rupy :D
Cada rotatoria da UNICAMP representa uma linguagem. Nas costas coloquei um QR Code com o site, que pode ser alterado para um conteudo mais divertido (bom pro marketing de voces).
[Camiseta Rupy.zip](https://github.com/rupycampinas/branding/files/166420/Camiseta.Rupy.zip)

Espero que gostem!
![Image]
(http://i.imgur.com/lNHlUrg.png)

**Comment by pedrobarrostech** [comment]
Bom dia, 

Segue minha ideia, espero que gostem!

Árvore do Conhecimento 
![rupy_shirt](https://cloud.githubusercontent.com/assets/5639968/14243259/cd493610-fa2a-11e5-8c1f-bf752672dec6.png)

[rupy-camiseta-arvoredeconhecimento.zip](https://github.com/rupycampinas/branding/files/202080/rupy-camiseta-arvoredeconhecimento.zip)

**Comment by guivr** [comment]
Modelo 2:
Vinho

![Modelo 2](http://i.imgur.com/wkZ42CY.png)

[Camiseta Rupy modelo2.zip](https://github.com/rupycampinas/branding/files/209509/Camiseta.Rupy.modelo2.zip)

**Comment by pedrobarrostech** [comment]
Quando fecha a promo?

**Comment by glaucocustodio** [comment]
Nenhuma das artes foi escolhidas pessoal, portanto, não houve ganhador. Obrigado pela participação de todos.

**Comment by guivr** [comment]
Obrigado por nos informar!
Vocês pelo menos poderiam ter feito isso antes, pois agora, com a venda de ingressos encerrada, não poderei ir!

**Comment by glaucocustodio** [comment]
Liberamos as inscrições até 12h de hoje. Dá tempo @guivr. Abs.

**Comment by pedrobarrostech** [comment]
Parabéns organização e consideração com os colaboradores :+1:
